# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

# all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
#all: contiki_inga
all: pc
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=shdt_cat.cpp
export BIN_OUT=shdt_cat
export WISELIB_EXIT_MAIN=1

export PC_COMPILE_DEBUG=1

#export PC_COMPILE_DEBUG=0
#export ADD_CXXFLAGS="-O3"

include ../Makefile
