all: pc

export APP_SRC=shdt_cat.cpp
export BIN_OUT=shdt_cat
export WISELIB_EXIT_MAIN=1

export PC_COMPILE_DEBUG=0
export ADD_CXXFLAGS="-O3 -DUSE_CODEC=0"

#export PC_COMPILE_DEBUG=1
#export ADD_CXXFLAGS="-DUSE_CODEC=0"


include ../Makefile
