#define SHAWN_PRIVACY_PC_APPLICATION
//#define PRIVACY_DEBUG
#define PRIVACY_CIPHER_TEXT_MAX_SIZE 80
#define PRIVACY_ENABLE_ENCRYPTION
#define PRIVACY_ENABLE_DECRYPTION
#define PRIVACY_ENABLE_RANDOMIZATION
#define PRIVACY_POWER_DB 0

