//#define PLTT_TRACKER
//#define PLTT_TARGET
#define CONFIG_PLTT_SECURE
#define UNIGE_TESTBED
//#define CTI_TESTBED
#define PLTT_MAX_NEIGHBORS_SUPPORTED 25
#define PLTT_MAX_TARGETS_SUPPORTED 5
#define PLTT_MAX_TRACKERS_SUPPORTED 5
#define PLTT_CHANNEL 20
#define PLTT_MAX_SECURE_TRACES_SUPPORTED 25
