# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

all: pc
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=example_app.cpp
export BIN_OUT=example_app
export PC_COMPILE_DEBUG=1
export WISELIB_DISABLE_DEBUG_MESSAGES=1

include ../Makefile
