# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

all: pc
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=codesize_app.cpp
export BIN_OUT=codesize_app
export PC_COMPILE_DEBUG=0
#export WISELIB_DISABLE_DEBUG_MESSAGES=1
export ADD_CXXFLAGS="-DWISELIB_DISABLE_DEBUG_MESSAGES=1 -Wall -DCODESIZE"
#export ADD_CXXFLAGS="-Wno-format -Wno-unused-local-typedefs"

include ../Makefile
