#define LINEAR_ADAPTATION
//#define TRICKLE_ADAPTATION

#define STATISTICS_ADM
#ifdef STATISTICS_ADM
#define STATISTICS_ADM_INTERVAL_CHANGES
#endif

#define DEBUG_ADM
#ifdef DEBUG_ADM
#define DEBUG_ADM_NODE_CHANGES
#define DEBUG_ADM_CONSISTENCY
#endif

#define ADM_CHECK_FOR_DROPPED
#define DEBUG_ADM_NODE_CHANGES
