# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('wiselib', ['core', 'wifi','internet'])
    module.source = [
        'model/wiselib-ext-iface.cc',
        'helper/wiselib-helper.cc',
        ]


    module_test = bld.create_ns3_module_test_library('wiselib')
    module_test.source = [
        'test/wiselib-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'wiselib'
    headers.source = [
        'model/wiselib-ext-iface.h',
        'helper/wiselib-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

