
#all: pc
#all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: contiki_sky
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz
# all: tinyos-telosb

export APP_SRC=codesize_test.cpp
export BIN_OUT=codesize_test

export ADD_CXXFLAGS="-Wno-write-strings"
export PC_COMPILE_DEBUG=0
export WISELIB_EXIT_MAIN=1

include ../Makefile
