
all: pc
#all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: contiki_sky
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz
# all: tinyos-telosb

export APP_SRC=rdfprovider_test.cpp
export BIN_OUT=rdfprovider_test

export ADD_CXXFLAGS="-Wno-write-strings"
export PC_COMPILE_DEBUG=1
export WISELIB_EXIT_MAIN=1

include ../Makefile
