# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

# all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
all: contiki_inga
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=example_app.cpp
export BIN_OUT=example_app
export PC_COMPILE_DEBUG=1
export WISELIB_EXIT_MAIN=1

include ../Makefile
