# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

# all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_sky
# all: contiki_micaz
all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=routing_test.cpp
export BIN_OUT=routing_test

include ../Makefile
