//enable switches from general to specific to more specific


//general switches
#define PLTT_OPT
//#define PLTT_METRICS
#define PLTT_DEBUG
#define PLTT_SECURE
//#define PLTT_TARGET_MINI_RUN
#define ISENSE_APP
//#define SHAWN_APP
#define LUEBECK_DEMO


//specific switches
//debug
#ifdef PLTT_DEBUG
	#define ISENSE_PLTT_PASSIVE_DEBUG
	#define ISENSE_PLTT_TARGET_DEBUG
	//#define ISENSE_PLTT_TRACKER_DEBUG
#endif
//optimizations
#ifdef PLTT_OPT
	#define OPT_SPREAD_RANDOM_RECEIVERS
	#define OPT_LQI_INHIBITION
	#define OPT_PATH_CORRECTION
	#define OPT_TARGET_LIST_AGGREGATION
	#define OPT_NON_MERGED_TREE
	#define OPT_RELIABLE_TRACKING
	#define OPT_FLOOD_NEIGHBORS
#endif

//metrics
#ifdef PLTT_METRICS
	#define PLTT_TRACKING_METRICS
	#define PLTT_SPREAD_METRICS
#endif

//metrics dependencies
#ifdef PLTT_TRACKING_METRICS
	#define PLTT_PASSIVE_TRACKING_METRICS
	#define PLTT_PASSIVE_TRACKING_METRICS_LIGHT
	#define PLTT_TRACKER_TRACKING_METRICS
	#define PLTT_AGENT_TRACKING_METRICS
	#define PLTT_TARGET_TRACKING_METRICS
#endif
#ifdef PLTT_SPREAD_METRICS
	#define PLTT_PASSIVE_SPREAD_METRICS
	#define PLTT_PASSIVE_SPREAD_METRICS_LIGHT
	#define PLTT_TARGET_SPREAD_METRICS
#endif

//metrics debug dependencies
#ifdef PLTT_METRICS
	#define ISENSE_PLTT_METRICS_DEBUG
#endif
#ifdef PLTT_SECURE
	#define ISENSE_PLTT_SECURE_DEBUG
#endif

//more specific switches
//debug
#ifdef ISENSE_PLTT_PASSIVE_DEBUG
	#define ISENSE_PLTT_PASSIVE_DEBUG_NEIGHBORHOOD_DISCOVERY
	#define ISENSE_PLTT_PASSIVE_DEBUG_SPREAD
	#define ISENSE_PLTT_PASSIVE_DEBUG_INHIBITION
	#define ISENSE_PLTT_PASSIVE_DEBUG_TRACK_ECHO
	#define ISENSE_PLTT_PASSIVE_DEBUG_TRACK_QUERY
	#define ISENSE_PLTT_PASSIVE_DEBUG_TRACK_QUERY_REPORT
	#define ISENSE_PLTT_PASSIVE_DEBUG_MISC
	#ifdef ISENSE_PLTT_SECURE_DEBUG
		#define ISENSE_PLTT_PASSIVE_DEBUG_SECURE
	#endif
	#ifdef ISENSE_PLTT_METRICS_DEBUG
		#define ISENSE_PLTT_METRICS_PASSIVE_DEBUG
	#endif
	#ifdef OPT_RELIABLE_TRACKING
		#define ISENSE_PLTT_PASSIVE_RELIABLE_TRACKING_DEBUG
	#endif
#endif
#ifdef ISENSE_PLTT_TARGET_DEBUG
	#define ISENSE_PLTT_TARGET_DEBUG_SEND
	#define ISENSE_PLTT_TARGET_DEBUG_MISC
	#ifdef PLTT_SECURE
		#define ISENSE_PLTT_TARGET_DEBUG_SECURE
	#endif
	#ifdef ISENSE_PLTT_METRICS_DEBUG
		#define ISENSE_PLTT_TARGET_METRICS_DEBUG
	#endif
#endif
#ifdef ISENSE_PLTT_TRACKER_DEBUG
	#define ISENSE_PLTT_TRACKER_DEBUG_REPORT
	#define ISENSE_PLTT_TRACKER_DEBUG_QUERY
	#define ISENSE_PLTT_TRACKER_DEBUG_MISC
	#ifdef ISENSE_PLTT_SECURE_DEBUG
		#define ISENSE_PLTT_TRACKER_DEBUG_SECURE
	#endif
	#ifdef ISENSE_PLTT_METRICS_DEBUG
		#define ISENSE_PLTT_METRICS_TRACKER_DEBUG
	#endif
#endif

