#!/bin/sh

PATTERN=$1
shift
ARGS=""

while [ $# -gt 1 ]; do
	ARGS="$ARGS $1"
	shift
done
FNAME=$1

#echo PAT $PATTERN
#echo ARGS $ARGS
#echo FNAME $FNAME

grep "$PATTERN"'\|BEGIN ITERATION' $ARGS $FNAME|grep "$PATTERN" $ARGS -B 1

