#define SHAWN_PRIVACY_PC_APPLICATION
//#define PRIVACY_DEBUG

#define PRIVACY_ENABLE_ENCRYPTION
#define PRIVACY_ENABLE_ENCRYPTION_OTA
#define PRIVACY_ENABLE_DECRYPTION
#define PRIVACY_ENABLE_DECRYPTION_OTA
#define PRIVACY_ENABLE_RANDOMIZATION
//#define PRIVACY_ENABLE_RANDOMIZATION_OTA


