# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

# all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
  all: isense.5148
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=sound_test.cpp
export BIN_OUT=sound_test

include ../Makefile
