# ------------------------------------------------
# Environment variable WISELIB_PATH_TESTING needed
# ------------------------------------------------

all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: contiki_sky
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz
# all: tinyos-telosb

export APP_SRC=uart_test.cpp
export BIN_OUT=uart_test

include ../Makefile