
all: pc
# all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: contiki_sky
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz
# all: tinyos-telosb

export APP_SRC=app_host.cpp
export BIN_OUT=app_host

export ADD_CXXFLAGS="-Wno-write-strings -m32"
export WISELIB_EXIT_MAIN=0
export PC_COMPILE_DEBUG=1

include ../Makefile

