#!/bin/sh

echo boot $(date) >>/tmp/log/timestamps
echo $(hostname) >/tmp/log/hostname.txt

sleep $((5 * 50))
#ls -l /dev/* >/tmp/log/ls_dev.txt

while :; do
        echo dump $(date) >>/tmp/log/timestamps

        #sudo stdbuf -oL -eL /tmp/mnt/serialdump-linux -b115200 /dev/tmotesky1 | while read l; do
        sudo stdbuf -oL -eL /tmp/mnt/app_host < incontextsensing.rdf | while read l; do
                echo $(date +'T%s.%N|')$l
        done >>/tmp/log/output.txt 2>>/tmp/log/error.txt 

        sleep 5
done



