
all: pc
# all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: contiki_sky
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz
# all: tinyos-telosb

export APP_SRC=tuplestore_example.cpp
export BIN_OUT=tuplestore_example

export ADD_CXXFLAGS="-Wno-write-strings"
export WISELIB_EXIT_MAIN=1

include ../Makefile

