// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Msg;
@class Msg_Builder;
@class SingleRequestMultipleResponseRequest;
@class SingleRequestMultipleResponseRequest_Builder;
@class SingleRequestMultipleResponseResponse;
@class SingleRequestMultipleResponseResponse_Builder;

@interface MessagesRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Msg : PBGeneratedMessage {
@private
  BOOL hasValidUntil_:1;
  BOOL hasTo_:1;
  BOOL hasFrom_:1;
  BOOL hasMsgType_:1;
  BOOL hasReplyWith_:1;
  BOOL hasReplyTo_:1;
  BOOL hasPayload_:1;
  BOOL hasPriority_:1;
  uint64_t validUntil;
  NSString* to;
  NSString* from;
  NSString* msgType;
  NSString* replyWith;
  NSString* replyTo;
  NSData* payload;
  uint32_t priority;
}
- (BOOL) hasTo;
- (BOOL) hasFrom;
- (BOOL) hasMsgType;
- (BOOL) hasPriority;
- (BOOL) hasValidUntil;
- (BOOL) hasPayload;
- (BOOL) hasReplyWith;
- (BOOL) hasReplyTo;
@property (readonly, retain) NSString* to;
@property (readonly, retain) NSString* from;
@property (readonly, retain) NSString* msgType;
@property (readonly) uint32_t priority;
@property (readonly) uint64_t validUntil;
@property (readonly, retain) NSData* payload;
@property (readonly, retain) NSString* replyWith;
@property (readonly, retain) NSString* replyTo;

+ (Msg*) defaultInstance;
- (Msg*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Msg_Builder*) builder;
+ (Msg_Builder*) builder;
+ (Msg_Builder*) builderWithPrototype:(Msg*) prototype;

+ (Msg*) parseFromData:(NSData*) data;
+ (Msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Msg*) parseFromInputStream:(NSInputStream*) input;
+ (Msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Msg_Builder : PBGeneratedMessage_Builder {
@private
  Msg* result;
}

- (Msg*) defaultInstance;

- (Msg_Builder*) clear;
- (Msg_Builder*) clone;

- (Msg*) build;
- (Msg*) buildPartial;

- (Msg_Builder*) mergeFrom:(Msg*) other;
- (Msg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Msg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTo;
- (NSString*) to;
- (Msg_Builder*) setTo:(NSString*) value;
- (Msg_Builder*) clearTo;

- (BOOL) hasFrom;
- (NSString*) from;
- (Msg_Builder*) setFrom:(NSString*) value;
- (Msg_Builder*) clearFrom;

- (BOOL) hasMsgType;
- (NSString*) msgType;
- (Msg_Builder*) setMsgType:(NSString*) value;
- (Msg_Builder*) clearMsgType;

- (BOOL) hasPriority;
- (uint32_t) priority;
- (Msg_Builder*) setPriority:(uint32_t) value;
- (Msg_Builder*) clearPriority;

- (BOOL) hasValidUntil;
- (uint64_t) validUntil;
- (Msg_Builder*) setValidUntil:(uint64_t) value;
- (Msg_Builder*) clearValidUntil;

- (BOOL) hasPayload;
- (NSData*) payload;
- (Msg_Builder*) setPayload:(NSData*) value;
- (Msg_Builder*) clearPayload;

- (BOOL) hasReplyWith;
- (NSString*) replyWith;
- (Msg_Builder*) setReplyWith:(NSString*) value;
- (Msg_Builder*) clearReplyWith;

- (BOOL) hasReplyTo;
- (NSString*) replyTo;
- (Msg_Builder*) setReplyTo:(NSString*) value;
- (Msg_Builder*) clearReplyTo;
@end

@interface SingleRequestMultipleResponseRequest : PBGeneratedMessage {
@private
  BOOL hasReliableRequest_:1;
  BOOL hasReliableResponses_:1;
  BOOL hasRequestId_:1;
  BOOL hasPayload_:1;
  BOOL reliableRequest_:1;
  BOOL reliableResponses_:1;
  NSString* requestId;
  NSData* payload;
}
- (BOOL) hasRequestId;
- (BOOL) hasReliableRequest;
- (BOOL) hasReliableResponses;
- (BOOL) hasPayload;
@property (readonly, retain) NSString* requestId;
- (BOOL) reliableRequest;
- (BOOL) reliableResponses;
@property (readonly, retain) NSData* payload;

+ (SingleRequestMultipleResponseRequest*) defaultInstance;
- (SingleRequestMultipleResponseRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SingleRequestMultipleResponseRequest_Builder*) builder;
+ (SingleRequestMultipleResponseRequest_Builder*) builder;
+ (SingleRequestMultipleResponseRequest_Builder*) builderWithPrototype:(SingleRequestMultipleResponseRequest*) prototype;

+ (SingleRequestMultipleResponseRequest*) parseFromData:(NSData*) data;
+ (SingleRequestMultipleResponseRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SingleRequestMultipleResponseRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SingleRequestMultipleResponseRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SingleRequestMultipleResponseRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SingleRequestMultipleResponseRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SingleRequestMultipleResponseRequest_Builder : PBGeneratedMessage_Builder {
@private
  SingleRequestMultipleResponseRequest* result;
}

- (SingleRequestMultipleResponseRequest*) defaultInstance;

- (SingleRequestMultipleResponseRequest_Builder*) clear;
- (SingleRequestMultipleResponseRequest_Builder*) clone;

- (SingleRequestMultipleResponseRequest*) build;
- (SingleRequestMultipleResponseRequest*) buildPartial;

- (SingleRequestMultipleResponseRequest_Builder*) mergeFrom:(SingleRequestMultipleResponseRequest*) other;
- (SingleRequestMultipleResponseRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SingleRequestMultipleResponseRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRequestId;
- (NSString*) requestId;
- (SingleRequestMultipleResponseRequest_Builder*) setRequestId:(NSString*) value;
- (SingleRequestMultipleResponseRequest_Builder*) clearRequestId;

- (BOOL) hasReliableRequest;
- (BOOL) reliableRequest;
- (SingleRequestMultipleResponseRequest_Builder*) setReliableRequest:(BOOL) value;
- (SingleRequestMultipleResponseRequest_Builder*) clearReliableRequest;

- (BOOL) hasReliableResponses;
- (BOOL) reliableResponses;
- (SingleRequestMultipleResponseRequest_Builder*) setReliableResponses:(BOOL) value;
- (SingleRequestMultipleResponseRequest_Builder*) clearReliableResponses;

- (BOOL) hasPayload;
- (NSData*) payload;
- (SingleRequestMultipleResponseRequest_Builder*) setPayload:(NSData*) value;
- (SingleRequestMultipleResponseRequest_Builder*) clearPayload;
@end

@interface SingleRequestMultipleResponseResponse : PBGeneratedMessage {
@private
  BOOL hasRequestId_:1;
  BOOL hasPayload_:1;
  NSString* requestId;
  NSData* payload;
}
- (BOOL) hasRequestId;
- (BOOL) hasPayload;
@property (readonly, retain) NSString* requestId;
@property (readonly, retain) NSData* payload;

+ (SingleRequestMultipleResponseResponse*) defaultInstance;
- (SingleRequestMultipleResponseResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SingleRequestMultipleResponseResponse_Builder*) builder;
+ (SingleRequestMultipleResponseResponse_Builder*) builder;
+ (SingleRequestMultipleResponseResponse_Builder*) builderWithPrototype:(SingleRequestMultipleResponseResponse*) prototype;

+ (SingleRequestMultipleResponseResponse*) parseFromData:(NSData*) data;
+ (SingleRequestMultipleResponseResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SingleRequestMultipleResponseResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SingleRequestMultipleResponseResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SingleRequestMultipleResponseResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SingleRequestMultipleResponseResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SingleRequestMultipleResponseResponse_Builder : PBGeneratedMessage_Builder {
@private
  SingleRequestMultipleResponseResponse* result;
}

- (SingleRequestMultipleResponseResponse*) defaultInstance;

- (SingleRequestMultipleResponseResponse_Builder*) clear;
- (SingleRequestMultipleResponseResponse_Builder*) clone;

- (SingleRequestMultipleResponseResponse*) build;
- (SingleRequestMultipleResponseResponse*) buildPartial;

- (SingleRequestMultipleResponseResponse_Builder*) mergeFrom:(SingleRequestMultipleResponseResponse*) other;
- (SingleRequestMultipleResponseResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SingleRequestMultipleResponseResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRequestId;
- (NSString*) requestId;
- (SingleRequestMultipleResponseResponse_Builder*) setRequestId:(NSString*) value;
- (SingleRequestMultipleResponseResponse_Builder*) clearRequestId;

- (BOOL) hasPayload;
- (NSData*) payload;
- (SingleRequestMultipleResponseResponse_Builder*) setPayload:(NSData*) value;
- (SingleRequestMultipleResponseResponse_Builder*) clearPayload;
@end

