// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "WSNAppMessages.pb.h"

@implementation WSNAppMessagesRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [WSNAppMessagesRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface ListenerManagement ()
@property ListenerManagement_Operation operation;
@property (retain) NSString* nodeName;
@end

@implementation ListenerManagement

- (BOOL) hasOperation {
  return !!hasOperation_;
}
- (void) setHasOperation:(BOOL) value {
  hasOperation_ = !!value;
}
@synthesize operation;
- (BOOL) hasNodeName {
  return !!hasNodeName_;
}
- (void) setHasNodeName:(BOOL) value {
  hasNodeName_ = !!value;
}
@synthesize nodeName;
- (void) dealloc {
  self.nodeName = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.operation = ListenerManagement_OperationRegister;
    self.nodeName = @"";
  }
  return self;
}
static ListenerManagement* defaultListenerManagementInstance = nil;
+ (void) initialize {
  if (self == [ListenerManagement class]) {
    defaultListenerManagementInstance = [[ListenerManagement alloc] init];
  }
}
+ (ListenerManagement*) defaultInstance {
  return defaultListenerManagementInstance;
}
- (ListenerManagement*) defaultInstance {
  return defaultListenerManagementInstance;
}
- (BOOL) isInitialized {
  if (!self.hasOperation) {
    return NO;
  }
  if (!self.hasNodeName) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasOperation) {
    [output writeEnum:1 value:self.operation];
  }
  if (self.hasNodeName) {
    [output writeString:2 value:self.nodeName];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasOperation) {
    size += computeEnumSize(1, self.operation);
  }
  if (self.hasNodeName) {
    size += computeStringSize(2, self.nodeName);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (ListenerManagement*) parseFromData:(NSData*) data {
  return (ListenerManagement*)[[[ListenerManagement builder] mergeFromData:data] build];
}
+ (ListenerManagement*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ListenerManagement*)[[[ListenerManagement builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ListenerManagement*) parseFromInputStream:(NSInputStream*) input {
  return (ListenerManagement*)[[[ListenerManagement builder] mergeFromInputStream:input] build];
}
+ (ListenerManagement*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ListenerManagement*)[[[ListenerManagement builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ListenerManagement*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ListenerManagement*)[[[ListenerManagement builder] mergeFromCodedInputStream:input] build];
}
+ (ListenerManagement*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ListenerManagement*)[[[ListenerManagement builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ListenerManagement_Builder*) builder {
  return [[[ListenerManagement_Builder alloc] init] autorelease];
}
+ (ListenerManagement_Builder*) builderWithPrototype:(ListenerManagement*) prototype {
  return [[ListenerManagement builder] mergeFrom:prototype];
}
- (ListenerManagement_Builder*) builder {
  return [ListenerManagement builder];
}
@end

BOOL ListenerManagement_OperationIsValidValue(ListenerManagement_Operation value) {
  switch (value) {
    case ListenerManagement_OperationRegister:
    case ListenerManagement_OperationUnregister:
      return YES;
    default:
      return NO;
  }
}
@interface ListenerManagement_Builder()
@property (retain) ListenerManagement* result;
@end

@implementation ListenerManagement_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ListenerManagement alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ListenerManagement_Builder*) clear {
  self.result = [[[ListenerManagement alloc] init] autorelease];
  return self;
}
- (ListenerManagement_Builder*) clone {
  return [ListenerManagement builderWithPrototype:result];
}
- (ListenerManagement*) defaultInstance {
  return [ListenerManagement defaultInstance];
}
- (ListenerManagement*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ListenerManagement*) buildPartial {
  ListenerManagement* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ListenerManagement_Builder*) mergeFrom:(ListenerManagement*) other {
  if (other == [ListenerManagement defaultInstance]) {
    return self;
  }
  if (other.hasOperation) {
    [self setOperation:other.operation];
  }
  if (other.hasNodeName) {
    [self setNodeName:other.nodeName];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ListenerManagement_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ListenerManagement_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        int32_t value = [input readEnum];
        if (ListenerManagement_OperationIsValidValue(value)) {
          [self setOperation:value];
        } else {
          [unknownFields mergeVarintField:1 value:value];
        }
        break;
      }
      case 18: {
        [self setNodeName:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasOperation {
  return result.hasOperation;
}
- (ListenerManagement_Operation) operation {
  return result.operation;
}
- (ListenerManagement_Builder*) setOperation:(ListenerManagement_Operation) value {
  result.hasOperation = YES;
  result.operation = value;
  return self;
}
- (ListenerManagement_Builder*) clearOperation {
  result.hasOperation = NO;
  result.operation = ListenerManagement_OperationRegister;
  return self;
}
- (BOOL) hasNodeName {
  return result.hasNodeName;
}
- (NSString*) nodeName {
  return result.nodeName;
}
- (ListenerManagement_Builder*) setNodeName:(NSString*) value {
  result.hasNodeName = YES;
  result.nodeName = value;
  return self;
}
- (ListenerManagement_Builder*) clearNodeName {
  result.hasNodeName = NO;
  result.nodeName = @"";
  return self;
}
@end

@interface RequestStatus ()
@property (retain) RequestStatus_Status* status;
@end

@implementation RequestStatus

- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
@synthesize status;
- (void) dealloc {
  self.status = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.status = [RequestStatus_Status defaultInstance];
  }
  return self;
}
static RequestStatus* defaultRequestStatusInstance = nil;
+ (void) initialize {
  if (self == [RequestStatus class]) {
    defaultRequestStatusInstance = [[RequestStatus alloc] init];
  }
}
+ (RequestStatus*) defaultInstance {
  return defaultRequestStatusInstance;
}
- (RequestStatus*) defaultInstance {
  return defaultRequestStatusInstance;
}
- (BOOL) isInitialized {
  if (!self.hasStatus) {
    return NO;
  }
  if (!self.status.isInitialized) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStatus) {
    [output writeMessage:1 value:self.status];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasStatus) {
    size += computeMessageSize(1, self.status);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (RequestStatus*) parseFromData:(NSData*) data {
  return (RequestStatus*)[[[RequestStatus builder] mergeFromData:data] build];
}
+ (RequestStatus*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestStatus*)[[[RequestStatus builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RequestStatus*) parseFromInputStream:(NSInputStream*) input {
  return (RequestStatus*)[[[RequestStatus builder] mergeFromInputStream:input] build];
}
+ (RequestStatus*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestStatus*)[[[RequestStatus builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestStatus*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RequestStatus*)[[[RequestStatus builder] mergeFromCodedInputStream:input] build];
}
+ (RequestStatus*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestStatus*)[[[RequestStatus builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestStatus_Builder*) builder {
  return [[[RequestStatus_Builder alloc] init] autorelease];
}
+ (RequestStatus_Builder*) builderWithPrototype:(RequestStatus*) prototype {
  return [[RequestStatus builder] mergeFrom:prototype];
}
- (RequestStatus_Builder*) builder {
  return [RequestStatus builder];
}
@end

@interface RequestStatus_Status ()
@property (retain) NSString* nodeId;
@property int32_t value;
@property (retain) NSString* msg;
@end

@implementation RequestStatus_Status

- (BOOL) hasNodeId {
  return !!hasNodeId_;
}
- (void) setHasNodeId:(BOOL) value {
  hasNodeId_ = !!value;
}
@synthesize nodeId;
- (BOOL) hasValue {
  return !!hasValue_;
}
- (void) setHasValue:(BOOL) value {
  hasValue_ = !!value;
}
@synthesize value;
- (BOOL) hasMsg {
  return !!hasMsg_;
}
- (void) setHasMsg:(BOOL) value {
  hasMsg_ = !!value;
}
@synthesize msg;
- (void) dealloc {
  self.nodeId = nil;
  self.msg = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.nodeId = @"";
    self.value = 0;
    self.msg = @"";
  }
  return self;
}
static RequestStatus_Status* defaultRequestStatus_StatusInstance = nil;
+ (void) initialize {
  if (self == [RequestStatus_Status class]) {
    defaultRequestStatus_StatusInstance = [[RequestStatus_Status alloc] init];
  }
}
+ (RequestStatus_Status*) defaultInstance {
  return defaultRequestStatus_StatusInstance;
}
- (RequestStatus_Status*) defaultInstance {
  return defaultRequestStatus_StatusInstance;
}
- (BOOL) isInitialized {
  if (!self.hasNodeId) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasNodeId) {
    [output writeString:1 value:self.nodeId];
  }
  if (self.hasValue) {
    [output writeInt32:2 value:self.value];
  }
  if (self.hasMsg) {
    [output writeString:3 value:self.msg];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasNodeId) {
    size += computeStringSize(1, self.nodeId);
  }
  if (self.hasValue) {
    size += computeInt32Size(2, self.value);
  }
  if (self.hasMsg) {
    size += computeStringSize(3, self.msg);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (RequestStatus_Status*) parseFromData:(NSData*) data {
  return (RequestStatus_Status*)[[[RequestStatus_Status builder] mergeFromData:data] build];
}
+ (RequestStatus_Status*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestStatus_Status*)[[[RequestStatus_Status builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RequestStatus_Status*) parseFromInputStream:(NSInputStream*) input {
  return (RequestStatus_Status*)[[[RequestStatus_Status builder] mergeFromInputStream:input] build];
}
+ (RequestStatus_Status*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestStatus_Status*)[[[RequestStatus_Status builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestStatus_Status*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RequestStatus_Status*)[[[RequestStatus_Status builder] mergeFromCodedInputStream:input] build];
}
+ (RequestStatus_Status*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestStatus_Status*)[[[RequestStatus_Status builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestStatus_Status_Builder*) builder {
  return [[[RequestStatus_Status_Builder alloc] init] autorelease];
}
+ (RequestStatus_Status_Builder*) builderWithPrototype:(RequestStatus_Status*) prototype {
  return [[RequestStatus_Status builder] mergeFrom:prototype];
}
- (RequestStatus_Status_Builder*) builder {
  return [RequestStatus_Status builder];
}
@end

@interface RequestStatus_Status_Builder()
@property (retain) RequestStatus_Status* result;
@end

@implementation RequestStatus_Status_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[RequestStatus_Status alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (RequestStatus_Status_Builder*) clear {
  self.result = [[[RequestStatus_Status alloc] init] autorelease];
  return self;
}
- (RequestStatus_Status_Builder*) clone {
  return [RequestStatus_Status builderWithPrototype:result];
}
- (RequestStatus_Status*) defaultInstance {
  return [RequestStatus_Status defaultInstance];
}
- (RequestStatus_Status*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RequestStatus_Status*) buildPartial {
  RequestStatus_Status* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (RequestStatus_Status_Builder*) mergeFrom:(RequestStatus_Status*) other {
  if (other == [RequestStatus_Status defaultInstance]) {
    return self;
  }
  if (other.hasNodeId) {
    [self setNodeId:other.nodeId];
  }
  if (other.hasValue) {
    [self setValue:other.value];
  }
  if (other.hasMsg) {
    [self setMsg:other.msg];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RequestStatus_Status_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RequestStatus_Status_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setNodeId:[input readString]];
        break;
      }
      case 16: {
        [self setValue:[input readInt32]];
        break;
      }
      case 26: {
        [self setMsg:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasNodeId {
  return result.hasNodeId;
}
- (NSString*) nodeId {
  return result.nodeId;
}
- (RequestStatus_Status_Builder*) setNodeId:(NSString*) value {
  result.hasNodeId = YES;
  result.nodeId = value;
  return self;
}
- (RequestStatus_Status_Builder*) clearNodeId {
  result.hasNodeId = NO;
  result.nodeId = @"";
  return self;
}
- (BOOL) hasValue {
  return result.hasValue;
}
- (int32_t) value {
  return result.value;
}
- (RequestStatus_Status_Builder*) setValue:(int32_t) value {
  result.hasValue = YES;
  result.value = value;
  return self;
}
- (RequestStatus_Status_Builder*) clearValue {
  result.hasValue = NO;
  result.value = 0;
  return self;
}
- (BOOL) hasMsg {
  return result.hasMsg;
}
- (NSString*) msg {
  return result.msg;
}
- (RequestStatus_Status_Builder*) setMsg:(NSString*) value {
  result.hasMsg = YES;
  result.msg = value;
  return self;
}
- (RequestStatus_Status_Builder*) clearMsg {
  result.hasMsg = NO;
  result.msg = @"";
  return self;
}
@end

@interface RequestStatus_Builder()
@property (retain) RequestStatus* result;
@end

@implementation RequestStatus_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[RequestStatus alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (RequestStatus_Builder*) clear {
  self.result = [[[RequestStatus alloc] init] autorelease];
  return self;
}
- (RequestStatus_Builder*) clone {
  return [RequestStatus builderWithPrototype:result];
}
- (RequestStatus*) defaultInstance {
  return [RequestStatus defaultInstance];
}
- (RequestStatus*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RequestStatus*) buildPartial {
  RequestStatus* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (RequestStatus_Builder*) mergeFrom:(RequestStatus*) other {
  if (other == [RequestStatus defaultInstance]) {
    return self;
  }
  if (other.hasStatus) {
    [self mergeStatus:other.status];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RequestStatus_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RequestStatus_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        RequestStatus_Status_Builder* subBuilder = [RequestStatus_Status builder];
        if (self.hasStatus) {
          [subBuilder mergeFrom:self.status];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setStatus:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (RequestStatus_Status*) status {
  return result.status;
}
- (RequestStatus_Builder*) setStatus:(RequestStatus_Status*) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (RequestStatus_Builder*) setStatusBuilder:(RequestStatus_Status_Builder*) builderForValue {
  return [self setStatus:[builderForValue build]];
}
- (RequestStatus_Builder*) mergeStatus:(RequestStatus_Status*) value {
  if (result.hasStatus &&
      result.status != [RequestStatus_Status defaultInstance]) {
    result.status =
      [[[RequestStatus_Status builderWithPrototype:result.status] mergeFrom:value] buildPartial];
  } else {
    result.status = value;
  }
  result.hasStatus = YES;
  return self;
}
- (RequestStatus_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = [RequestStatus_Status defaultInstance];
  return self;
}
@end

@interface Program ()
@property (retain) NSData* program;
@property (retain) Program_ProgramMetaData* metaData;
@end

@implementation Program

- (BOOL) hasProgram {
  return !!hasProgram_;
}
- (void) setHasProgram:(BOOL) value {
  hasProgram_ = !!value;
}
@synthesize program;
- (BOOL) hasMetaData {
  return !!hasMetaData_;
}
- (void) setHasMetaData:(BOOL) value {
  hasMetaData_ = !!value;
}
@synthesize metaData;
- (void) dealloc {
  self.program = nil;
  self.metaData = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.program = [NSData data];
    self.metaData = [Program_ProgramMetaData defaultInstance];
  }
  return self;
}
static Program* defaultProgramInstance = nil;
+ (void) initialize {
  if (self == [Program class]) {
    defaultProgramInstance = [[Program alloc] init];
  }
}
+ (Program*) defaultInstance {
  return defaultProgramInstance;
}
- (Program*) defaultInstance {
  return defaultProgramInstance;
}
- (BOOL) isInitialized {
  if (!self.hasProgram) {
    return NO;
  }
  if (self.hasMetaData) {
    if (!self.metaData.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasProgram) {
    [output writeData:1 value:self.program];
  }
  if (self.hasMetaData) {
    [output writeMessage:2 value:self.metaData];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasProgram) {
    size += computeDataSize(1, self.program);
  }
  if (self.hasMetaData) {
    size += computeMessageSize(2, self.metaData);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Program*) parseFromData:(NSData*) data {
  return (Program*)[[[Program builder] mergeFromData:data] build];
}
+ (Program*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Program*)[[[Program builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Program*) parseFromInputStream:(NSInputStream*) input {
  return (Program*)[[[Program builder] mergeFromInputStream:input] build];
}
+ (Program*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Program*)[[[Program builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Program*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Program*)[[[Program builder] mergeFromCodedInputStream:input] build];
}
+ (Program*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Program*)[[[Program builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Program_Builder*) builder {
  return [[[Program_Builder alloc] init] autorelease];
}
+ (Program_Builder*) builderWithPrototype:(Program*) prototype {
  return [[Program builder] mergeFrom:prototype];
}
- (Program_Builder*) builder {
  return [Program builder];
}
@end

@interface Program_ProgramMetaData ()
@property (retain) NSString* version;
@property (retain) NSString* name;
@property (retain) NSString* platform;
@property (retain) NSString* other;
@end

@implementation Program_ProgramMetaData

- (BOOL) hasVersion {
  return !!hasVersion_;
}
- (void) setHasVersion:(BOOL) value {
  hasVersion_ = !!value;
}
@synthesize version;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value {
  hasName_ = !!value;
}
@synthesize name;
- (BOOL) hasPlatform {
  return !!hasPlatform_;
}
- (void) setHasPlatform:(BOOL) value {
  hasPlatform_ = !!value;
}
@synthesize platform;
- (BOOL) hasOther {
  return !!hasOther_;
}
- (void) setHasOther:(BOOL) value {
  hasOther_ = !!value;
}
@synthesize other;
- (void) dealloc {
  self.version = nil;
  self.name = nil;
  self.platform = nil;
  self.other = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.version = @"";
    self.name = @"";
    self.platform = @"";
    self.other = @"";
  }
  return self;
}
static Program_ProgramMetaData* defaultProgram_ProgramMetaDataInstance = nil;
+ (void) initialize {
  if (self == [Program_ProgramMetaData class]) {
    defaultProgram_ProgramMetaDataInstance = [[Program_ProgramMetaData alloc] init];
  }
}
+ (Program_ProgramMetaData*) defaultInstance {
  return defaultProgram_ProgramMetaDataInstance;
}
- (Program_ProgramMetaData*) defaultInstance {
  return defaultProgram_ProgramMetaDataInstance;
}
- (BOOL) isInitialized {
  if (!self.hasVersion) {
    return NO;
  }
  if (!self.hasName) {
    return NO;
  }
  if (!self.hasPlatform) {
    return NO;
  }
  if (!self.hasOther) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasVersion) {
    [output writeString:1 value:self.version];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  if (self.hasPlatform) {
    [output writeString:3 value:self.platform];
  }
  if (self.hasOther) {
    [output writeString:4 value:self.other];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasVersion) {
    size += computeStringSize(1, self.version);
  }
  if (self.hasName) {
    size += computeStringSize(2, self.name);
  }
  if (self.hasPlatform) {
    size += computeStringSize(3, self.platform);
  }
  if (self.hasOther) {
    size += computeStringSize(4, self.other);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Program_ProgramMetaData*) parseFromData:(NSData*) data {
  return (Program_ProgramMetaData*)[[[Program_ProgramMetaData builder] mergeFromData:data] build];
}
+ (Program_ProgramMetaData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Program_ProgramMetaData*)[[[Program_ProgramMetaData builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Program_ProgramMetaData*) parseFromInputStream:(NSInputStream*) input {
  return (Program_ProgramMetaData*)[[[Program_ProgramMetaData builder] mergeFromInputStream:input] build];
}
+ (Program_ProgramMetaData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Program_ProgramMetaData*)[[[Program_ProgramMetaData builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Program_ProgramMetaData*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Program_ProgramMetaData*)[[[Program_ProgramMetaData builder] mergeFromCodedInputStream:input] build];
}
+ (Program_ProgramMetaData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Program_ProgramMetaData*)[[[Program_ProgramMetaData builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Program_ProgramMetaData_Builder*) builder {
  return [[[Program_ProgramMetaData_Builder alloc] init] autorelease];
}
+ (Program_ProgramMetaData_Builder*) builderWithPrototype:(Program_ProgramMetaData*) prototype {
  return [[Program_ProgramMetaData builder] mergeFrom:prototype];
}
- (Program_ProgramMetaData_Builder*) builder {
  return [Program_ProgramMetaData builder];
}
@end

@interface Program_ProgramMetaData_Builder()
@property (retain) Program_ProgramMetaData* result;
@end

@implementation Program_ProgramMetaData_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Program_ProgramMetaData alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Program_ProgramMetaData_Builder*) clear {
  self.result = [[[Program_ProgramMetaData alloc] init] autorelease];
  return self;
}
- (Program_ProgramMetaData_Builder*) clone {
  return [Program_ProgramMetaData builderWithPrototype:result];
}
- (Program_ProgramMetaData*) defaultInstance {
  return [Program_ProgramMetaData defaultInstance];
}
- (Program_ProgramMetaData*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Program_ProgramMetaData*) buildPartial {
  Program_ProgramMetaData* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Program_ProgramMetaData_Builder*) mergeFrom:(Program_ProgramMetaData*) other {
  if (other == [Program_ProgramMetaData defaultInstance]) {
    return self;
  }
  if (other.hasVersion) {
    [self setVersion:other.version];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasPlatform) {
    [self setPlatform:other.platform];
  }
  if (other.hasOther) {
    [self setOther:other.other];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Program_ProgramMetaData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Program_ProgramMetaData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setVersion:[input readString]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
      case 26: {
        [self setPlatform:[input readString]];
        break;
      }
      case 34: {
        [self setOther:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasVersion {
  return result.hasVersion;
}
- (NSString*) version {
  return result.version;
}
- (Program_ProgramMetaData_Builder*) setVersion:(NSString*) value {
  result.hasVersion = YES;
  result.version = value;
  return self;
}
- (Program_ProgramMetaData_Builder*) clearVersion {
  result.hasVersion = NO;
  result.version = @"";
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (Program_ProgramMetaData_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (Program_ProgramMetaData_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasPlatform {
  return result.hasPlatform;
}
- (NSString*) platform {
  return result.platform;
}
- (Program_ProgramMetaData_Builder*) setPlatform:(NSString*) value {
  result.hasPlatform = YES;
  result.platform = value;
  return self;
}
- (Program_ProgramMetaData_Builder*) clearPlatform {
  result.hasPlatform = NO;
  result.platform = @"";
  return self;
}
- (BOOL) hasOther {
  return result.hasOther;
}
- (NSString*) other {
  return result.other;
}
- (Program_ProgramMetaData_Builder*) setOther:(NSString*) value {
  result.hasOther = YES;
  result.other = value;
  return self;
}
- (Program_ProgramMetaData_Builder*) clearOther {
  result.hasOther = NO;
  result.other = @"";
  return self;
}
@end

@interface Program_Builder()
@property (retain) Program* result;
@end

@implementation Program_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Program alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Program_Builder*) clear {
  self.result = [[[Program alloc] init] autorelease];
  return self;
}
- (Program_Builder*) clone {
  return [Program builderWithPrototype:result];
}
- (Program*) defaultInstance {
  return [Program defaultInstance];
}
- (Program*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Program*) buildPartial {
  Program* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Program_Builder*) mergeFrom:(Program*) other {
  if (other == [Program defaultInstance]) {
    return self;
  }
  if (other.hasProgram) {
    [self setProgram:other.program];
  }
  if (other.hasMetaData) {
    [self mergeMetaData:other.metaData];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Program_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Program_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setProgram:[input readData]];
        break;
      }
      case 18: {
        Program_ProgramMetaData_Builder* subBuilder = [Program_ProgramMetaData builder];
        if (self.hasMetaData) {
          [subBuilder mergeFrom:self.metaData];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setMetaData:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasProgram {
  return result.hasProgram;
}
- (NSData*) program {
  return result.program;
}
- (Program_Builder*) setProgram:(NSData*) value {
  result.hasProgram = YES;
  result.program = value;
  return self;
}
- (Program_Builder*) clearProgram {
  result.hasProgram = NO;
  result.program = [NSData data];
  return self;
}
- (BOOL) hasMetaData {
  return result.hasMetaData;
}
- (Program_ProgramMetaData*) metaData {
  return result.metaData;
}
- (Program_Builder*) setMetaData:(Program_ProgramMetaData*) value {
  result.hasMetaData = YES;
  result.metaData = value;
  return self;
}
- (Program_Builder*) setMetaDataBuilder:(Program_ProgramMetaData_Builder*) builderForValue {
  return [self setMetaData:[builderForValue build]];
}
- (Program_Builder*) mergeMetaData:(Program_ProgramMetaData*) value {
  if (result.hasMetaData &&
      result.metaData != [Program_ProgramMetaData defaultInstance]) {
    result.metaData =
      [[[Program_ProgramMetaData builderWithPrototype:result.metaData] mergeFrom:value] buildPartial];
  } else {
    result.metaData = value;
  }
  result.hasMetaData = YES;
  return self;
}
- (Program_Builder*) clearMetaData {
  result.hasMetaData = NO;
  result.metaData = [Program_ProgramMetaData defaultInstance];
  return self;
}
@end

@interface Notification ()
@property (retain) NSString* message;
@end

@implementation Notification

- (BOOL) hasMessage {
  return !!hasMessage_;
}
- (void) setHasMessage:(BOOL) value {
  hasMessage_ = !!value;
}
@synthesize message;
- (void) dealloc {
  self.message = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.message = @"";
  }
  return self;
}
static Notification* defaultNotificationInstance = nil;
+ (void) initialize {
  if (self == [Notification class]) {
    defaultNotificationInstance = [[Notification alloc] init];
  }
}
+ (Notification*) defaultInstance {
  return defaultNotificationInstance;
}
- (Notification*) defaultInstance {
  return defaultNotificationInstance;
}
- (BOOL) isInitialized {
  if (!self.hasMessage) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasMessage) {
    [output writeString:1 value:self.message];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasMessage) {
    size += computeStringSize(1, self.message);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Notification*) parseFromData:(NSData*) data {
  return (Notification*)[[[Notification builder] mergeFromData:data] build];
}
+ (Notification*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Notification*)[[[Notification builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Notification*) parseFromInputStream:(NSInputStream*) input {
  return (Notification*)[[[Notification builder] mergeFromInputStream:input] build];
}
+ (Notification*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Notification*)[[[Notification builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Notification*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Notification*)[[[Notification builder] mergeFromCodedInputStream:input] build];
}
+ (Notification*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Notification*)[[[Notification builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Notification_Builder*) builder {
  return [[[Notification_Builder alloc] init] autorelease];
}
+ (Notification_Builder*) builderWithPrototype:(Notification*) prototype {
  return [[Notification builder] mergeFrom:prototype];
}
- (Notification_Builder*) builder {
  return [Notification builder];
}
@end

@interface Notification_Builder()
@property (retain) Notification* result;
@end

@implementation Notification_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Notification alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Notification_Builder*) clear {
  self.result = [[[Notification alloc] init] autorelease];
  return self;
}
- (Notification_Builder*) clone {
  return [Notification builderWithPrototype:result];
}
- (Notification*) defaultInstance {
  return [Notification defaultInstance];
}
- (Notification*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Notification*) buildPartial {
  Notification* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Notification_Builder*) mergeFrom:(Notification*) other {
  if (other == [Notification defaultInstance]) {
    return self;
  }
  if (other.hasMessage) {
    [self setMessage:other.message];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Notification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Notification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setMessage:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasMessage {
  return result.hasMessage;
}
- (NSString*) message {
  return result.message;
}
- (Notification_Builder*) setMessage:(NSString*) value {
  result.hasMessage = YES;
  result.message = value;
  return self;
}
- (Notification_Builder*) clearMessage {
  result.hasMessage = NO;
  result.message = @"";
  return self;
}
@end

@interface Message ()
@property (retain) NSString* sourceNodeId;
@property (retain) NSString* timestamp;
@property (retain) NSData* binaryData;
@end

@implementation Message

- (BOOL) hasSourceNodeId {
  return !!hasSourceNodeId_;
}
- (void) setHasSourceNodeId:(BOOL) value {
  hasSourceNodeId_ = !!value;
}
@synthesize sourceNodeId;
- (BOOL) hasTimestamp {
  return !!hasTimestamp_;
}
- (void) setHasTimestamp:(BOOL) value {
  hasTimestamp_ = !!value;
}
@synthesize timestamp;
- (BOOL) hasBinaryData {
  return !!hasBinaryData_;
}
- (void) setHasBinaryData:(BOOL) value {
  hasBinaryData_ = !!value;
}
@synthesize binaryData;
- (void) dealloc {
  self.sourceNodeId = nil;
  self.timestamp = nil;
  self.binaryData = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.sourceNodeId = @"";
    self.timestamp = @"";
    self.binaryData = [NSData data];
  }
  return self;
}
static Message* defaultMessageInstance = nil;
+ (void) initialize {
  if (self == [Message class]) {
    defaultMessageInstance = [[Message alloc] init];
  }
}
+ (Message*) defaultInstance {
  return defaultMessageInstance;
}
- (Message*) defaultInstance {
  return defaultMessageInstance;
}
- (BOOL) isInitialized {
  if (!self.hasSourceNodeId) {
    return NO;
  }
  if (!self.hasTimestamp) {
    return NO;
  }
  if (!self.hasBinaryData) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSourceNodeId) {
    [output writeString:1 value:self.sourceNodeId];
  }
  if (self.hasTimestamp) {
    [output writeString:2 value:self.timestamp];
  }
  if (self.hasBinaryData) {
    [output writeData:3 value:self.binaryData];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasSourceNodeId) {
    size += computeStringSize(1, self.sourceNodeId);
  }
  if (self.hasTimestamp) {
    size += computeStringSize(2, self.timestamp);
  }
  if (self.hasBinaryData) {
    size += computeDataSize(3, self.binaryData);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Message*) parseFromData:(NSData*) data {
  return (Message*)[[[Message builder] mergeFromData:data] build];
}
+ (Message*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message*)[[[Message builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message*) parseFromInputStream:(NSInputStream*) input {
  return (Message*)[[[Message builder] mergeFromInputStream:input] build];
}
+ (Message*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message*)[[[Message builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message*)[[[Message builder] mergeFromCodedInputStream:input] build];
}
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message*)[[[Message builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_Builder*) builder {
  return [[[Message_Builder alloc] init] autorelease];
}
+ (Message_Builder*) builderWithPrototype:(Message*) prototype {
  return [[Message builder] mergeFrom:prototype];
}
- (Message_Builder*) builder {
  return [Message builder];
}
@end

@interface Message_Builder()
@property (retain) Message* result;
@end

@implementation Message_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Message alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Message_Builder*) clear {
  self.result = [[[Message alloc] init] autorelease];
  return self;
}
- (Message_Builder*) clone {
  return [Message builderWithPrototype:result];
}
- (Message*) defaultInstance {
  return [Message defaultInstance];
}
- (Message*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message*) buildPartial {
  Message* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Message_Builder*) mergeFrom:(Message*) other {
  if (other == [Message defaultInstance]) {
    return self;
  }
  if (other.hasSourceNodeId) {
    [self setSourceNodeId:other.sourceNodeId];
  }
  if (other.hasTimestamp) {
    [self setTimestamp:other.timestamp];
  }
  if (other.hasBinaryData) {
    [self setBinaryData:other.binaryData];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setSourceNodeId:[input readString]];
        break;
      }
      case 18: {
        [self setTimestamp:[input readString]];
        break;
      }
      case 26: {
        [self setBinaryData:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasSourceNodeId {
  return result.hasSourceNodeId;
}
- (NSString*) sourceNodeId {
  return result.sourceNodeId;
}
- (Message_Builder*) setSourceNodeId:(NSString*) value {
  result.hasSourceNodeId = YES;
  result.sourceNodeId = value;
  return self;
}
- (Message_Builder*) clearSourceNodeId {
  result.hasSourceNodeId = NO;
  result.sourceNodeId = @"";
  return self;
}
- (BOOL) hasTimestamp {
  return result.hasTimestamp;
}
- (NSString*) timestamp {
  return result.timestamp;
}
- (Message_Builder*) setTimestamp:(NSString*) value {
  result.hasTimestamp = YES;
  result.timestamp = value;
  return self;
}
- (Message_Builder*) clearTimestamp {
  result.hasTimestamp = NO;
  result.timestamp = @"";
  return self;
}
- (BOOL) hasBinaryData {
  return result.hasBinaryData;
}
- (NSData*) binaryData {
  return result.binaryData;
}
- (Message_Builder*) setBinaryData:(NSData*) value {
  result.hasBinaryData = YES;
  result.binaryData = value;
  return self;
}
- (Message_Builder*) clearBinaryData {
  result.hasBinaryData = NO;
  result.binaryData = [NSData data];
  return self;
}
@end

@interface SetVirtualLinkRequest ()
@property (retain) NSString* sourceNode;
@property (retain) NSString* targetNode;
@end

@implementation SetVirtualLinkRequest

- (BOOL) hasSourceNode {
  return !!hasSourceNode_;
}
- (void) setHasSourceNode:(BOOL) value {
  hasSourceNode_ = !!value;
}
@synthesize sourceNode;
- (BOOL) hasTargetNode {
  return !!hasTargetNode_;
}
- (void) setHasTargetNode:(BOOL) value {
  hasTargetNode_ = !!value;
}
@synthesize targetNode;
- (void) dealloc {
  self.sourceNode = nil;
  self.targetNode = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.sourceNode = @"";
    self.targetNode = @"";
  }
  return self;
}
static SetVirtualLinkRequest* defaultSetVirtualLinkRequestInstance = nil;
+ (void) initialize {
  if (self == [SetVirtualLinkRequest class]) {
    defaultSetVirtualLinkRequestInstance = [[SetVirtualLinkRequest alloc] init];
  }
}
+ (SetVirtualLinkRequest*) defaultInstance {
  return defaultSetVirtualLinkRequestInstance;
}
- (SetVirtualLinkRequest*) defaultInstance {
  return defaultSetVirtualLinkRequestInstance;
}
- (BOOL) isInitialized {
  if (!self.hasSourceNode) {
    return NO;
  }
  if (!self.hasTargetNode) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSourceNode) {
    [output writeString:1 value:self.sourceNode];
  }
  if (self.hasTargetNode) {
    [output writeString:2 value:self.targetNode];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasSourceNode) {
    size += computeStringSize(1, self.sourceNode);
  }
  if (self.hasTargetNode) {
    size += computeStringSize(2, self.targetNode);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (SetVirtualLinkRequest*) parseFromData:(NSData*) data {
  return (SetVirtualLinkRequest*)[[[SetVirtualLinkRequest builder] mergeFromData:data] build];
}
+ (SetVirtualLinkRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SetVirtualLinkRequest*)[[[SetVirtualLinkRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (SetVirtualLinkRequest*) parseFromInputStream:(NSInputStream*) input {
  return (SetVirtualLinkRequest*)[[[SetVirtualLinkRequest builder] mergeFromInputStream:input] build];
}
+ (SetVirtualLinkRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SetVirtualLinkRequest*)[[[SetVirtualLinkRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SetVirtualLinkRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (SetVirtualLinkRequest*)[[[SetVirtualLinkRequest builder] mergeFromCodedInputStream:input] build];
}
+ (SetVirtualLinkRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SetVirtualLinkRequest*)[[[SetVirtualLinkRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SetVirtualLinkRequest_Builder*) builder {
  return [[[SetVirtualLinkRequest_Builder alloc] init] autorelease];
}
+ (SetVirtualLinkRequest_Builder*) builderWithPrototype:(SetVirtualLinkRequest*) prototype {
  return [[SetVirtualLinkRequest builder] mergeFrom:prototype];
}
- (SetVirtualLinkRequest_Builder*) builder {
  return [SetVirtualLinkRequest builder];
}
@end

@interface SetVirtualLinkRequest_Builder()
@property (retain) SetVirtualLinkRequest* result;
@end

@implementation SetVirtualLinkRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[SetVirtualLinkRequest alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (SetVirtualLinkRequest_Builder*) clear {
  self.result = [[[SetVirtualLinkRequest alloc] init] autorelease];
  return self;
}
- (SetVirtualLinkRequest_Builder*) clone {
  return [SetVirtualLinkRequest builderWithPrototype:result];
}
- (SetVirtualLinkRequest*) defaultInstance {
  return [SetVirtualLinkRequest defaultInstance];
}
- (SetVirtualLinkRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (SetVirtualLinkRequest*) buildPartial {
  SetVirtualLinkRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (SetVirtualLinkRequest_Builder*) mergeFrom:(SetVirtualLinkRequest*) other {
  if (other == [SetVirtualLinkRequest defaultInstance]) {
    return self;
  }
  if (other.hasSourceNode) {
    [self setSourceNode:other.sourceNode];
  }
  if (other.hasTargetNode) {
    [self setTargetNode:other.targetNode];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (SetVirtualLinkRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (SetVirtualLinkRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setSourceNode:[input readString]];
        break;
      }
      case 18: {
        [self setTargetNode:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasSourceNode {
  return result.hasSourceNode;
}
- (NSString*) sourceNode {
  return result.sourceNode;
}
- (SetVirtualLinkRequest_Builder*) setSourceNode:(NSString*) value {
  result.hasSourceNode = YES;
  result.sourceNode = value;
  return self;
}
- (SetVirtualLinkRequest_Builder*) clearSourceNode {
  result.hasSourceNode = NO;
  result.sourceNode = @"";
  return self;
}
- (BOOL) hasTargetNode {
  return result.hasTargetNode;
}
- (NSString*) targetNode {
  return result.targetNode;
}
- (SetVirtualLinkRequest_Builder*) setTargetNode:(NSString*) value {
  result.hasTargetNode = YES;
  result.targetNode = value;
  return self;
}
- (SetVirtualLinkRequest_Builder*) clearTargetNode {
  result.hasTargetNode = NO;
  result.targetNode = @"";
  return self;
}
@end

@interface DestroyVirtualLinkRequest ()
@property (retain) NSString* sourceNode;
@property (retain) NSString* targetNode;
@end

@implementation DestroyVirtualLinkRequest

- (BOOL) hasSourceNode {
  return !!hasSourceNode_;
}
- (void) setHasSourceNode:(BOOL) value {
  hasSourceNode_ = !!value;
}
@synthesize sourceNode;
- (BOOL) hasTargetNode {
  return !!hasTargetNode_;
}
- (void) setHasTargetNode:(BOOL) value {
  hasTargetNode_ = !!value;
}
@synthesize targetNode;
- (void) dealloc {
  self.sourceNode = nil;
  self.targetNode = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.sourceNode = @"";
    self.targetNode = @"";
  }
  return self;
}
static DestroyVirtualLinkRequest* defaultDestroyVirtualLinkRequestInstance = nil;
+ (void) initialize {
  if (self == [DestroyVirtualLinkRequest class]) {
    defaultDestroyVirtualLinkRequestInstance = [[DestroyVirtualLinkRequest alloc] init];
  }
}
+ (DestroyVirtualLinkRequest*) defaultInstance {
  return defaultDestroyVirtualLinkRequestInstance;
}
- (DestroyVirtualLinkRequest*) defaultInstance {
  return defaultDestroyVirtualLinkRequestInstance;
}
- (BOOL) isInitialized {
  if (!self.hasSourceNode) {
    return NO;
  }
  if (!self.hasTargetNode) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSourceNode) {
    [output writeString:1 value:self.sourceNode];
  }
  if (self.hasTargetNode) {
    [output writeString:2 value:self.targetNode];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasSourceNode) {
    size += computeStringSize(1, self.sourceNode);
  }
  if (self.hasTargetNode) {
    size += computeStringSize(2, self.targetNode);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (DestroyVirtualLinkRequest*) parseFromData:(NSData*) data {
  return (DestroyVirtualLinkRequest*)[[[DestroyVirtualLinkRequest builder] mergeFromData:data] build];
}
+ (DestroyVirtualLinkRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DestroyVirtualLinkRequest*)[[[DestroyVirtualLinkRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (DestroyVirtualLinkRequest*) parseFromInputStream:(NSInputStream*) input {
  return (DestroyVirtualLinkRequest*)[[[DestroyVirtualLinkRequest builder] mergeFromInputStream:input] build];
}
+ (DestroyVirtualLinkRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DestroyVirtualLinkRequest*)[[[DestroyVirtualLinkRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DestroyVirtualLinkRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (DestroyVirtualLinkRequest*)[[[DestroyVirtualLinkRequest builder] mergeFromCodedInputStream:input] build];
}
+ (DestroyVirtualLinkRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DestroyVirtualLinkRequest*)[[[DestroyVirtualLinkRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DestroyVirtualLinkRequest_Builder*) builder {
  return [[[DestroyVirtualLinkRequest_Builder alloc] init] autorelease];
}
+ (DestroyVirtualLinkRequest_Builder*) builderWithPrototype:(DestroyVirtualLinkRequest*) prototype {
  return [[DestroyVirtualLinkRequest builder] mergeFrom:prototype];
}
- (DestroyVirtualLinkRequest_Builder*) builder {
  return [DestroyVirtualLinkRequest builder];
}
@end

@interface DestroyVirtualLinkRequest_Builder()
@property (retain) DestroyVirtualLinkRequest* result;
@end

@implementation DestroyVirtualLinkRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[DestroyVirtualLinkRequest alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (DestroyVirtualLinkRequest_Builder*) clear {
  self.result = [[[DestroyVirtualLinkRequest alloc] init] autorelease];
  return self;
}
- (DestroyVirtualLinkRequest_Builder*) clone {
  return [DestroyVirtualLinkRequest builderWithPrototype:result];
}
- (DestroyVirtualLinkRequest*) defaultInstance {
  return [DestroyVirtualLinkRequest defaultInstance];
}
- (DestroyVirtualLinkRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (DestroyVirtualLinkRequest*) buildPartial {
  DestroyVirtualLinkRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (DestroyVirtualLinkRequest_Builder*) mergeFrom:(DestroyVirtualLinkRequest*) other {
  if (other == [DestroyVirtualLinkRequest defaultInstance]) {
    return self;
  }
  if (other.hasSourceNode) {
    [self setSourceNode:other.sourceNode];
  }
  if (other.hasTargetNode) {
    [self setTargetNode:other.targetNode];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (DestroyVirtualLinkRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (DestroyVirtualLinkRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setSourceNode:[input readString]];
        break;
      }
      case 18: {
        [self setTargetNode:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasSourceNode {
  return result.hasSourceNode;
}
- (NSString*) sourceNode {
  return result.sourceNode;
}
- (DestroyVirtualLinkRequest_Builder*) setSourceNode:(NSString*) value {
  result.hasSourceNode = YES;
  result.sourceNode = value;
  return self;
}
- (DestroyVirtualLinkRequest_Builder*) clearSourceNode {
  result.hasSourceNode = NO;
  result.sourceNode = @"";
  return self;
}
- (BOOL) hasTargetNode {
  return result.hasTargetNode;
}
- (NSString*) targetNode {
  return result.targetNode;
}
- (DestroyVirtualLinkRequest_Builder*) setTargetNode:(NSString*) value {
  result.hasTargetNode = YES;
  result.targetNode = value;
  return self;
}
- (DestroyVirtualLinkRequest_Builder*) clearTargetNode {
  result.hasTargetNode = NO;
  result.targetNode = @"";
  return self;
}
@end

@interface DisablePhysicalLink ()
@property (retain) NSString* nodeB;
@end

@implementation DisablePhysicalLink

- (BOOL) hasNodeB {
  return !!hasNodeB_;
}
- (void) setHasNodeB:(BOOL) value {
  hasNodeB_ = !!value;
}
@synthesize nodeB;
- (void) dealloc {
  self.nodeB = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.nodeB = @"";
  }
  return self;
}
static DisablePhysicalLink* defaultDisablePhysicalLinkInstance = nil;
+ (void) initialize {
  if (self == [DisablePhysicalLink class]) {
    defaultDisablePhysicalLinkInstance = [[DisablePhysicalLink alloc] init];
  }
}
+ (DisablePhysicalLink*) defaultInstance {
  return defaultDisablePhysicalLinkInstance;
}
- (DisablePhysicalLink*) defaultInstance {
  return defaultDisablePhysicalLinkInstance;
}
- (BOOL) isInitialized {
  if (!self.hasNodeB) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasNodeB) {
    [output writeString:2 value:self.nodeB];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasNodeB) {
    size += computeStringSize(2, self.nodeB);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (DisablePhysicalLink*) parseFromData:(NSData*) data {
  return (DisablePhysicalLink*)[[[DisablePhysicalLink builder] mergeFromData:data] build];
}
+ (DisablePhysicalLink*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DisablePhysicalLink*)[[[DisablePhysicalLink builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (DisablePhysicalLink*) parseFromInputStream:(NSInputStream*) input {
  return (DisablePhysicalLink*)[[[DisablePhysicalLink builder] mergeFromInputStream:input] build];
}
+ (DisablePhysicalLink*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DisablePhysicalLink*)[[[DisablePhysicalLink builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DisablePhysicalLink*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (DisablePhysicalLink*)[[[DisablePhysicalLink builder] mergeFromCodedInputStream:input] build];
}
+ (DisablePhysicalLink*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DisablePhysicalLink*)[[[DisablePhysicalLink builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DisablePhysicalLink_Builder*) builder {
  return [[[DisablePhysicalLink_Builder alloc] init] autorelease];
}
+ (DisablePhysicalLink_Builder*) builderWithPrototype:(DisablePhysicalLink*) prototype {
  return [[DisablePhysicalLink builder] mergeFrom:prototype];
}
- (DisablePhysicalLink_Builder*) builder {
  return [DisablePhysicalLink builder];
}
@end

@interface DisablePhysicalLink_Builder()
@property (retain) DisablePhysicalLink* result;
@end

@implementation DisablePhysicalLink_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[DisablePhysicalLink alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (DisablePhysicalLink_Builder*) clear {
  self.result = [[[DisablePhysicalLink alloc] init] autorelease];
  return self;
}
- (DisablePhysicalLink_Builder*) clone {
  return [DisablePhysicalLink builderWithPrototype:result];
}
- (DisablePhysicalLink*) defaultInstance {
  return [DisablePhysicalLink defaultInstance];
}
- (DisablePhysicalLink*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (DisablePhysicalLink*) buildPartial {
  DisablePhysicalLink* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (DisablePhysicalLink_Builder*) mergeFrom:(DisablePhysicalLink*) other {
  if (other == [DisablePhysicalLink defaultInstance]) {
    return self;
  }
  if (other.hasNodeB) {
    [self setNodeB:other.nodeB];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (DisablePhysicalLink_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (DisablePhysicalLink_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 18: {
        [self setNodeB:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasNodeB {
  return result.hasNodeB;
}
- (NSString*) nodeB {
  return result.nodeB;
}
- (DisablePhysicalLink_Builder*) setNodeB:(NSString*) value {
  result.hasNodeB = YES;
  result.nodeB = value;
  return self;
}
- (DisablePhysicalLink_Builder*) clearNodeB {
  result.hasNodeB = NO;
  result.nodeB = @"";
  return self;
}
@end

@interface EnablePhysicalLink ()
@property (retain) NSString* nodeB;
@end

@implementation EnablePhysicalLink

- (BOOL) hasNodeB {
  return !!hasNodeB_;
}
- (void) setHasNodeB:(BOOL) value {
  hasNodeB_ = !!value;
}
@synthesize nodeB;
- (void) dealloc {
  self.nodeB = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.nodeB = @"";
  }
  return self;
}
static EnablePhysicalLink* defaultEnablePhysicalLinkInstance = nil;
+ (void) initialize {
  if (self == [EnablePhysicalLink class]) {
    defaultEnablePhysicalLinkInstance = [[EnablePhysicalLink alloc] init];
  }
}
+ (EnablePhysicalLink*) defaultInstance {
  return defaultEnablePhysicalLinkInstance;
}
- (EnablePhysicalLink*) defaultInstance {
  return defaultEnablePhysicalLinkInstance;
}
- (BOOL) isInitialized {
  if (!self.hasNodeB) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasNodeB) {
    [output writeString:2 value:self.nodeB];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasNodeB) {
    size += computeStringSize(2, self.nodeB);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (EnablePhysicalLink*) parseFromData:(NSData*) data {
  return (EnablePhysicalLink*)[[[EnablePhysicalLink builder] mergeFromData:data] build];
}
+ (EnablePhysicalLink*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (EnablePhysicalLink*)[[[EnablePhysicalLink builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (EnablePhysicalLink*) parseFromInputStream:(NSInputStream*) input {
  return (EnablePhysicalLink*)[[[EnablePhysicalLink builder] mergeFromInputStream:input] build];
}
+ (EnablePhysicalLink*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (EnablePhysicalLink*)[[[EnablePhysicalLink builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (EnablePhysicalLink*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (EnablePhysicalLink*)[[[EnablePhysicalLink builder] mergeFromCodedInputStream:input] build];
}
+ (EnablePhysicalLink*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (EnablePhysicalLink*)[[[EnablePhysicalLink builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (EnablePhysicalLink_Builder*) builder {
  return [[[EnablePhysicalLink_Builder alloc] init] autorelease];
}
+ (EnablePhysicalLink_Builder*) builderWithPrototype:(EnablePhysicalLink*) prototype {
  return [[EnablePhysicalLink builder] mergeFrom:prototype];
}
- (EnablePhysicalLink_Builder*) builder {
  return [EnablePhysicalLink builder];
}
@end

@interface EnablePhysicalLink_Builder()
@property (retain) EnablePhysicalLink* result;
@end

@implementation EnablePhysicalLink_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[EnablePhysicalLink alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (EnablePhysicalLink_Builder*) clear {
  self.result = [[[EnablePhysicalLink alloc] init] autorelease];
  return self;
}
- (EnablePhysicalLink_Builder*) clone {
  return [EnablePhysicalLink builderWithPrototype:result];
}
- (EnablePhysicalLink*) defaultInstance {
  return [EnablePhysicalLink defaultInstance];
}
- (EnablePhysicalLink*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (EnablePhysicalLink*) buildPartial {
  EnablePhysicalLink* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (EnablePhysicalLink_Builder*) mergeFrom:(EnablePhysicalLink*) other {
  if (other == [EnablePhysicalLink defaultInstance]) {
    return self;
  }
  if (other.hasNodeB) {
    [self setNodeB:other.nodeB];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (EnablePhysicalLink_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (EnablePhysicalLink_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 18: {
        [self setNodeB:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasNodeB {
  return result.hasNodeB;
}
- (NSString*) nodeB {
  return result.nodeB;
}
- (EnablePhysicalLink_Builder*) setNodeB:(NSString*) value {
  result.hasNodeB = YES;
  result.nodeB = value;
  return self;
}
- (EnablePhysicalLink_Builder*) clearNodeB {
  result.hasNodeB = NO;
  result.nodeB = @"";
  return self;
}
@end

@interface OperationInvocation ()
@property OperationInvocation_Operation operation;
@property (retain) NSData* arguments;
@end

@implementation OperationInvocation

- (BOOL) hasOperation {
  return !!hasOperation_;
}
- (void) setHasOperation:(BOOL) value {
  hasOperation_ = !!value;
}
@synthesize operation;
- (BOOL) hasArguments {
  return !!hasArguments_;
}
- (void) setHasArguments:(BOOL) value {
  hasArguments_ = !!value;
}
@synthesize arguments;
- (void) dealloc {
  self.arguments = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.operation = OperationInvocation_OperationSend;
    self.arguments = [NSData data];
  }
  return self;
}
static OperationInvocation* defaultOperationInvocationInstance = nil;
+ (void) initialize {
  if (self == [OperationInvocation class]) {
    defaultOperationInvocationInstance = [[OperationInvocation alloc] init];
  }
}
+ (OperationInvocation*) defaultInstance {
  return defaultOperationInvocationInstance;
}
- (OperationInvocation*) defaultInstance {
  return defaultOperationInvocationInstance;
}
- (BOOL) isInitialized {
  if (!self.hasOperation) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasOperation) {
    [output writeEnum:1 value:self.operation];
  }
  if (self.hasArguments) {
    [output writeData:2 value:self.arguments];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasOperation) {
    size += computeEnumSize(1, self.operation);
  }
  if (self.hasArguments) {
    size += computeDataSize(2, self.arguments);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (OperationInvocation*) parseFromData:(NSData*) data {
  return (OperationInvocation*)[[[OperationInvocation builder] mergeFromData:data] build];
}
+ (OperationInvocation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (OperationInvocation*)[[[OperationInvocation builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (OperationInvocation*) parseFromInputStream:(NSInputStream*) input {
  return (OperationInvocation*)[[[OperationInvocation builder] mergeFromInputStream:input] build];
}
+ (OperationInvocation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (OperationInvocation*)[[[OperationInvocation builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (OperationInvocation*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (OperationInvocation*)[[[OperationInvocation builder] mergeFromCodedInputStream:input] build];
}
+ (OperationInvocation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (OperationInvocation*)[[[OperationInvocation builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (OperationInvocation_Builder*) builder {
  return [[[OperationInvocation_Builder alloc] init] autorelease];
}
+ (OperationInvocation_Builder*) builderWithPrototype:(OperationInvocation*) prototype {
  return [[OperationInvocation builder] mergeFrom:prototype];
}
- (OperationInvocation_Builder*) builder {
  return [OperationInvocation builder];
}
@end

BOOL OperationInvocation_OperationIsValidValue(OperationInvocation_Operation value) {
  switch (value) {
    case OperationInvocation_OperationSend:
    case OperationInvocation_OperationAreNodesAlive:
    case OperationInvocation_OperationFlashPrograms:
    case OperationInvocation_OperationResetNodes:
    case OperationInvocation_OperationSetVirtualLink:
    case OperationInvocation_OperationDestroyVirtualLink:
    case OperationInvocation_OperationDisableNode:
    case OperationInvocation_OperationEnableNode:
    case OperationInvocation_OperationDisablePhysicalLink:
    case OperationInvocation_OperationEnablePhysicalLink:
      return YES;
    default:
      return NO;
  }
}
@interface OperationInvocation_Builder()
@property (retain) OperationInvocation* result;
@end

@implementation OperationInvocation_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[OperationInvocation alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (OperationInvocation_Builder*) clear {
  self.result = [[[OperationInvocation alloc] init] autorelease];
  return self;
}
- (OperationInvocation_Builder*) clone {
  return [OperationInvocation builderWithPrototype:result];
}
- (OperationInvocation*) defaultInstance {
  return [OperationInvocation defaultInstance];
}
- (OperationInvocation*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (OperationInvocation*) buildPartial {
  OperationInvocation* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (OperationInvocation_Builder*) mergeFrom:(OperationInvocation*) other {
  if (other == [OperationInvocation defaultInstance]) {
    return self;
  }
  if (other.hasOperation) {
    [self setOperation:other.operation];
  }
  if (other.hasArguments) {
    [self setArguments:other.arguments];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (OperationInvocation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (OperationInvocation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        int32_t value = [input readEnum];
        if (OperationInvocation_OperationIsValidValue(value)) {
          [self setOperation:value];
        } else {
          [unknownFields mergeVarintField:1 value:value];
        }
        break;
      }
      case 18: {
        [self setArguments:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasOperation {
  return result.hasOperation;
}
- (OperationInvocation_Operation) operation {
  return result.operation;
}
- (OperationInvocation_Builder*) setOperation:(OperationInvocation_Operation) value {
  result.hasOperation = YES;
  result.operation = value;
  return self;
}
- (OperationInvocation_Builder*) clearOperation {
  result.hasOperation = NO;
  result.operation = OperationInvocation_OperationSend;
  return self;
}
- (BOOL) hasArguments {
  return result.hasArguments;
}
- (NSData*) arguments {
  return result.arguments;
}
- (OperationInvocation_Builder*) setArguments:(NSData*) value {
  result.hasArguments = YES;
  result.arguments = value;
  return self;
}
- (OperationInvocation_Builder*) clearArguments {
  result.hasArguments = NO;
  result.arguments = [NSData data];
  return self;
}
@end

