#------------------------------------------------------------------------------
#-- DO NOT TOUCH - Modify Makefile.properties instead
#------------------------------------------------------------------------------

include Makefile.properties


LD	= msp430-gcc
CCP	= msp430-g++
CC 	= msp430-gcc
AR 	= msp430-ar
AS 	= msp430-as
SIZE = msp430-size
OBJCOPY = msp430-objcopy

SRC_PATH = src
OBJS_PATH = bin/msp430

#------------------------------------------------------------------------------
#-- Set up the C compiler flags
#------------------------------------------------------------------------------

LOCAL_COMMON_FLAGS =  -Isrc
LOCAL_COMMON_FLAGS += -I$(ISENSE_PATH)/src
LOCAL_COMMON_FLAGS += -DISENSE_MSP430
LOCAL_COMMON_FLAGS += -DNDEBUG -Os -mmcu=msp430x1611
LOCAL_COMMON_FLAGS += -I$(WISELIB_PATH_TESTING)
LOCAL_COMMON_FLAGS += -I$(WISELIB_PATH)

LOCAL_CFLAGS = 
LOCAL_CPPFLAGS = -fno-exceptions -fconserve-space -fno-implicit-inline-templates -fno-rtti

CFLAGS   += $(LOCAL_COMMON_FLAGS) $(LOCAL_CFLAGS)
CPPFLAGS += $(LOCAL_COMMON_FLAGS) $(LOCAL_CPPFLAGS)

#------------------------------------------------------------------------------
#-- Set up the linker libraries
#------------------------------------------------------------------------------

LIBFILE =
LIBFILE += $(ISENSE_PATH)/lib/msp430/iSenseLibraryMSP430.a  

#------------------------------------------------------------------------------
#-- This converts the *.c/*.S source file names to the output file names in
#-- the binary folder
#------------------------------------------------------------------------------

TMP_C_OBJECTS  = $(filter %.o,$(BLDSRCS:.c=.o))   
TMP_CPP_OBJECTS= $(filter %.o,$(BLDSRCS:.cpp=.o))   

C_OBJECTS  =$(TMP_C_OBJECTS:%=$(OBJS_PATH)/%)
CPP_OBJECTS=$(TMP_CPP_OBJECTS:%=$(OBJS_PATH)/%)

OBJECTS = $(C_OBJECTS) $(CPP_OBJECTS)

#------------------------------------------------------------------------------
#-- Build rules for the main application
#------------------------------------------------------------------------------

all: buildbin

buildbin: $(OBJS_PATH)/$(TARGET).ihex Makefile

debug:
	@echo -e "\n----- Objects of this build -------------------------- \
	\n\tSources    : $(BLDSRCS) \
	\n\tObjects    : $(OBJECTS) \
	\n\tLibfiles   : $(LIBFILE) \
	"

#------------------------------------------------------------------------------
#-- Build rules for the .c files
#------------------------------------------------------------------------------
	
$(OBJS_PATH)/%.o: $(SRC_PATH)/%.cpp
	@echo "----- Compiling (MSP430) $<"
	mkdir -p `dirname $@`
	$(CCP) $(CPPFLAGS) -MMD -c $< -o $@	
	mv $(@:%.o=%.d) $(@:%.o=%.P)


$(OBJS_PATH)/%.o: $(SRC_PATH)/%.c
	@echo "----- Compiling (MSP430) $<"
	mkdir -p `dirname $@`
	$(CC) $(CFLAGS) -MMD -c $< -o $@	
	mv $(@:%.o=%.d) $(@:%.o=%.P)

#------------------------------------------------------------------------------
#-- Linker
#------------------------------------------------------------------------------

$(OBJS_PATH)/$(TARGET).elf: $(OBJECTS) $(LIBFILE)
	@echo "----- Linking to $@"
	#$(LD) -T$(CHIP_BASE)/Build/$(LINKER_FILE) --gc-sections -z muldefs -o $@ $(LDFLAGS) $(OBJECTS) $(LIBFILE)
	$(LD)  -mmcu=msp430x1611 -T$(ISENSE_PATH)/lib/msp430/msp430x1611.x --gc-sections -u main -o $@ $(LDFLAGS) $(OBJECTS) $(LIBFILE) 

#------------------------------------------------------------------------------
#-- Copy the .or32 file to a .bin file
#------------------------------------------------------------------------------

$(OBJS_PATH)/$(TARGET).ihex: $(OBJS_PATH)/$(TARGET).elf
	@echo "----- Copying to ihex $<"
	#$(STRIP) $<
	$(SIZE) $<
	$(OBJCOPY) -S -O ihex $< $@


#------------------------------------------------------------------------------
#--  
#------------------------------------------------------------------------------

clean:
	rm -rf $(OBJS_PATH)

#------------------------------------------------------------------------------
#-- End
#------------------------------------------------------------------------------
.PRECIOUS: %.o %.ihex
.PHONY: all buildbin debug buildlibs
.SUFFIXES:

#------------------------------------------------------------------------------
# Dependency lists
#------------------------------------------------------------------------------
-include $(BLDSRCS:%.c=$(OBJS_PATH)/%.P)
-include $(BLDSRCS:%.cpp=$(OBJS_PATH)/%.P)
