{ "<http://spitfire-project.eu/sensor/sensor1234>", "<http://www.w3.org/2000/01/rdf-schema#type>", "<http://purl.oclc.org/NET/ssnx/ssn#Sensor>" },
{ "<http://spitfire-project.eu/sensor/sensor1234>", "<http://purl.oclc.org/NET/ssnx/ssn#observedProperty>", "<http://spitfire-project.eu/property/Temperature>" },
{ "<http://spitfire-project.eu/sensor/sensor1234>", "<http://www.loa-cnr.it/ontologies/DUL.owl#hasValue>", "12" },
{ "<http://spitfire-project.eu/property/Temperature>", "<http://purl.oclc.org/NET/muo/muo#measuredIn>", "<http://spitfire-project.eu/uom/Centigrade>" },
{ "<http://spitfire-project.eu/sensor/sensor1234>", "<http://purl.oclc.org/NET/ssnx/ssn#featureOfInterest>", "<http://spitfire-project.eu/foi/Room_12>" },
{ "<http://spitfire-project.eu/foi/Room_12>", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>", "<http://spitfire-project.eu/foi/Room>" },
