{ "<http://foo.bar/sensor123>", "<http://purl.oclc.org/NET/ssnx/ssn#observedProperty>", "<http://me.exmpl/Temperature>" },
{ "<http://foo.bar/sensor123>", "<http://www.ontologydesignpatterns.org/ont/dul/hasValue>", "1234" },
{ "<http://foo.bar/sensor123>", "<http://www.ontologydesignpatterns.org/ont/dul/hasValue>", "5678" },
{ "<http://foo.bar/sensor123>", "<http://purl.oclc.org/NET/ssnx/ssn#featureOfInterest>", "<http://foo.bar/room456>" },
{ "<http://foo.bar/room456>", "<http://www.ontologydesignpatterns.org/ont/dul/hasLocation>", "<http://me.exmpl/DERI>" },
