# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

all: shawn isense
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=neighbor_discovery_app.cpp
export BIN_OUT=neighbor_discovery_app

include ../Makefile
